### ISSUE TITLE
Zebra Banner: It Prints on the shield borders

### ISSUE THREAD

**Issue by ChezOverHere** [Itskillerluc/recrafted_creatures#1]
If you combine a banner with the zebra banner pattern, it prints on the border of the shield. First screenshot is the one with the new banner pattern while the other is a vanilla banner on shield just to demonstrate.

![image](https://github.com/Itskillerluc/recrafted_creatures/assets/144171520/b267224e-adcf-4e57-ac91-404575646ab9)
![image](https://github.com/Itskillerluc/recrafted_creatures/assets/144171520/d1478154-c19d-4df0-95d9-a685bd00e0c5)

**Comment by Lvgraef** [comment]
@ChezOverHere In order to fix this I will need a seperate new texture file for the shield.

**Comment by ChezOverHere** [comment]
Ok,

So do I need to just send a plain/empty texture?
![shield](https://github.com/Itskillerluc/recrafted_creatures/assets/144171520/21b76a6c-a5ea-467e-a883-8f7ff7102136)

**Comment by Lvgraef** [comment]
No here is an example of the skull one, this is for the shield:
![image](https://github.com/Itskillerluc/recrafted_creatures/assets/86008039/16aed131-7e0e-4978-a8f2-4734d89f7e7e)

This one is for the banner:
![image](https://github.com/Itskillerluc/recrafted_creatures/assets/86008039/a47ab800-cd1f-48cb-93c3-e5fa609dcc97)

It will just wrap it around the shield so you have to make it fit.

**Comment by ChezOverHere** [comment]
![image](https://github.com/Itskillerluc/recrafted_creatures/assets/144171520/6f23da93-00ff-48eb-8fb1-5b18f19bdfa6)
This should work

**Comment by Lvgraef** [comment]
![image](https://github.com/Itskillerluc/recrafted_creatures/assets/86008039/1305adff-786d-496e-a9c3-13cab42c65d5)
Fixed

**Comment by ChezOverHere** [comment]
Cool! :D 

I'm assuming it also fixes the back of the shield too?

**Comment by Lvgraef** [comment]
yes it does

**Comment by ChezOverHere** [comment]
Okay, good!
