### ISSUE TITLE
New Blocks

### ISSUE THREAD

**Issue by TheGBZard** [Itskillerluc/recrafted_creatures#19]
The Owl Egg, Chameleon Egg, Envelope and Rainbow Jell Block should all be added

Owl Eggs spawn in clutches of 1-3 and have a 30 minute gestation time with 10 minutes spent in each stage

Chameleon Eggs spawn in clutches of 1-4 and have a 15 minute gestation time with 5 minutes spent in each stage

Envelope is crafted with 2 paper and you can place 1 item or block into it and right click on it on the ground to get the items, you can put 1 stack of something in it. You can also right click on the owl to give it and right click again to take it.

When a chameleon eats silverfish, cave spiders, slimes or magma cubes they will drop a rainbow jell block. They are normal blocks but will change their colors like jeb_ sheep

- [x] Owl egg
- [x] Chameleon egg
- [x] envelope
- [x] rainbow jell block

**Comment by Lvgraef** [comment]
Waiting for the Rainbow jell blcok
