### ISSUE TITLE
The Megaphone is too big when dropped on the ground

### ISSUE THREAD

**Issue by TheGBZard** [Itskillerluc/recrafted_creatures#32]
![image](https://github.com/Itskillerluc/recrafted_creatures/assets/101367831/5970ce7c-0dae-4e13-a6f5-009f7eea9d43)

**Comment by Lvgraef** [comment]
![image](https://github.com/Itskillerluc/recrafted_creatures/assets/86008039/4a17ff92-8042-48ee-b0e2-327c1a64c868)
