### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by NantaArthur123** [Itskillerluc/recrafted_creatures#42]
Hi, been loving the screenshot of your mobs! I want to ask is there a plan to upload the mod to modrinth? thank you~

**Comment by Lvgraef** [comment]
Yes, I actually thought it already was on modrinth, but It is not, I will add it soon! I’m glad you like the mod.

**Comment by Lvgraef** [comment]
Gonna be uploaded next update which is gonna come out soon.
