### ISSUE TITLE
Zebra Issues

### ISSUE THREAD

**Issue by TheGBZard1903** [Itskillerluc/recrafted_creatures#46]
Provoked Zebras dont do any damage upon attacking

Zebras which run away from the player dont use the gallop animation

When jumping, the back legs dont stand still

Tamed Zebras always follow the player

**Comment by TheGBZard1903** [comment]
actually nevermind about the zebras always following, dont worry about that

**Comment by Lvgraef** [comment]
Cannot reproduce the first issue, the others are fixed.
