### ISSUE TITLE
Orangutan Issues

### ISSUE THREAD

**Issue by TheGBZard1903** [Itskillerluc/recrafted_creatures#51]
Orangutans cannot be tamed or bred, they should be tamed and bred with fruit kebabs, along with fruit kebabs being how they barter

Orangutan Climbing animation is also broken

**Comment by Lvgraef** [comment]
The orangutan isn't tameable, as per the information i received for the mob. The barter and breeding items are apples, which is also the information i received. But i can change that easily if you want.

**Comment by Lvgraef** [comment]
changed the bartering and breeding to fruit kebab
