### ISSUE TITLE
Stat variation not working for Zebras + Zebra health bugged

### ISSUE THREAD

**Issue by H311F1R3** [Itskillerluc/recrafted_creatures#62]
As of version 1.4.1 for 1.20.1, the stat variation for the zebras isnt working. The speed and jump distance of zebras are all stuck at the same value: 2.89 for jump height, and 9.48 for blocks. Health does vary correctly, but sometimes the babies get a hp of like 53 or 55 while all the others have hp in the low 20s. Didnt know if i shouldve made this a seperate issue but im already talking abt Zebra health so it fit. I have pics if proof is needed.

**Comment by Lvgraef** [comment]
I have come to the conclusion that this is a vanilla bug, and because the zebra uses some code from the horse it inherits this bug.
