### ISSUE TITLE
Orangutan Server Crash

### ISSUE THREAD

**Issue by Archidodo** [Itskillerluc/recrafted_creatures#64]
Server Crash Log :
https://gist.github.com/Archidodo/ac4184accb2cf9ae544ab4a631636430

Server seems to crash when an orangutan loads in.

I was playing with a friend doing a stronghold situated under a jungle when the server crashed and gave me this crash log.
I can start the server again but it crashes as soon as someone logs in and I guess the orangutan renders.
Also, it only crashes the server, the client is fine (I was not able to recreate the crash in a singleplayer world)

**Comment by Lvgraef** [comment]
i have uploaded a fix to CF

**Comment by Archidodo** [comment]
I can confirm the server is not crashing anymore, thanks!
